import React, { useState, useEffect } from "react";
import { Button } from "react-bootstrap";
import renderField from "./renderField";
import Grid from "@material-ui/core/Grid";

const { ethereum } = window;
const StepThree = () => {
  const [metaid, setMetaid] = useState("");
  useEffect(() => {
    // Web3 Browswer Detection
    if (typeof window.ethereum !== "undefined") {
      // console.log("Injected Web3 Wallet is installed!");
    }

    //Button ID
    const connectButton = document.getElementById("connect");

    //Click Event
    connectButton.addEventListener("click", () => {
      connectAccount();
    });

    //Connect Account Function
    async function connectAccount() {
      const accounts = await ethereum.request({
        method: "eth_requestAccounts",
      });
      const account = accounts[0];
      connectButton.innerHTML =
        account[0] +
        account[1] +
        account[2] +
        account[3] +
        account[4] +
        account[5] +
        "..." +
        account[38] +
        account[39] +
        account[40] +
        account[41];
      // console.log(accounts);
      setMetaid(accounts);
      // setValue("Sucessfully connected, Account:   " + accounts);
      connectButton.innerHTML = "Connect to Metamask";
    }
  }, []);
  return (
    <form>
      <div className="col-md-12">
        <h5>
          <b>Connect your wallet</b>
        </h5>
        <br />
        <div className="d-grid gap-2 ">
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <Grid textAlign="center">
            <Button
              // onClick={connectAccount}
              id="connect"
              className="me-2"
              variant="outline-primary"
              //   justifyContent="center"
              //   textAlign="center"
              size="lg"
              // onClick={connect}
            >
              Connect to Metamask
            </Button>
          </Grid>
        </div>
        <br />
        <div className=" btn-card bg-white text-success mt-3 ">
          <input className="form-control" value={metaid} type="text" />
        </div>
      </div>
      <br />
    </form>
  );
};

export default StepThree;
