/* Client Data */
export const GET_ADMIN_INSIGHT = "GET_ADMIN_INSIGHT";
export const ERR_ADMIN_INSIGHT = "ERR_ADMIN_INSIGHT";
export const SUCCESS_ADMIN_INSIGHT = "SUCCESS_ADMIN_INSIGHT";

export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";
export const ERR_DASHBOARD_DATA = "ERR_DASHBOARD_DATA";
export const SUCCESS_DASHBOARD_DATA = "SUCCESS_DASHBOARD_DATA";

export const GET_CLIENT_ACTION = "GET_CLIENT_ACTION";
export const ERR_GET_CLIENT_ACTION = "ERR_CLIENT_ACTION";
export const SUCCESS_GET_CLIENT_ACTION = "SUCCESS_CLIENT_ACTION";

export const UPDATE_CLIENT_ACTION = "UPDATE_CLIENT_ACTION";
export const ERR_UPDATE_CLIENT_ACTION = "ERR_UPDATE_CLIENT_ACTION";
export const SUCCESS_UPDATE_CLIENT_ACTION = "SUCCESS_UPDATE_CLIENT_ACTION";
export const REMOVE_MSG_UPDATE_CLIENT_ACTION =
  "REMOVE_SUCCESS_MSG_UPDATE_CLIENT_ACTION";

export const UPDATE_PACKAGE_STATUS_ACTION = "UPDATE_PACKAGE_STATUS_ACTION";
export const ERR_UPDATE_PACKAGE_STATUS_ACTION =
  "ERR_UPDATE_PACKAGE_STATUS_ACTION";
export const SUCCESS_UPDATE_PACKAGE_STATUS_ACTION =
  "SUCCESS_UPDATE_PACKAGE_STATUS_ACTION";
export const REMOVE_MSG_UPDATE_PACKAGE_STATUS_ACTION =
  "REMOVE_SUCCESS_MSG_UPDATE_PACKAGE_STATUS_ACTION";

export const GET_PACKAGE_ACTION = "GET_PACKAGE_ACTION";
export const ERR_GET_PACKAGE_ACTION = "ERR_PACKAGE_ACTION";
export const SUCCESS_GET_PACKAGE_ACTION = "SUCCESS_PACKAGE_ACTION";

export const CREATE_PACKAGE_ACTION = "CREATE_PACKAGE_ACTION";
export const ERR_CREATE_PACKAGE_ACTION = "ERR_CREATE_PACKAGE_ACTION";
export const SUCCESS_CREATE_PACKAGE_ACTION = "SUCCESS_CREATE_PACKAGE_ACTION";
export const REMOVE_MSG_CREATE_PACKAGE_ACTION =
  "REMOVE_SUCCESS_MSG_CREATE_PACKAGE_ACTION";

export const UPDATE_PACKAGE_ACTION = "UPDATE_PACKAGE_ACTION";
export const ERR_UPDATE_PACKAGE_ACTION = "ERR_UPDATE_PACKAGE_ACTION";
export const SUCCESS_UPDATE_PACKAGE_ACTION = "SUCCESS_UPDATE_PACKAGE_ACTION";
export const REMOVE_MSG_UPDATE_PACKAGE_ACTION =
  "REMOVE_SUCCESS_MSG_UPDATE_PACKAGE_ACTION";

export const ADD_DOMAIN_ACTION = "ADD_DOMAIN_ACTION";
export const ADD_DOMAIN_SUCCESS_ACTION = "ADD_DOMAIN_SUCCESS_ACTION";
export const ADD_DOMAIN_ERROR_ACTION = "ADD_DOMAIN_ERROR_ACTION";
export const ADD_DOMAIN_DONE = " ADD_DOMAIN_DONE";

export const UPDATE_DOMAIN_ACTION = "UPDATE_DOMAIN_ACTION";
export const UPDATE_DOMAIN_SUCCESS_ACTION = "UPDATE_DOMAIN_SUCCESS_ACTION";
export const UPDATE_DOMAIN_ERROR_ACTION = "UPDATE_DOMAIN_ERROR_ACTION";
export const UPDATE_DOMAIN_DONE = "UPDATE_DOMAIN_DONE";

export const GET_DOMAIN_ACTION = "GET_DOMAIN_ACTION";
export const GET_DOMAIN_SUCCESS_ACTION = "GET_DOMAIN_SUCCESS_ACTION";
export const GET_DOMAIN_ERROR_ACTION = "GET_DOMAIN_ERROR_ACTION";

export const GET_STORE_ACTION = "GET_STORE_ACTION";
export const GET_STORE_SUCCESS_ACTION = "GET_STORE_SUCCESS_ACTION";
export const GET_STORE_ERROR_ACTION = "GET_STORE_ERROR_ACTION";

export const UPDATE_STORE_ACTION = "UPDATE_STORE_ACTION";
export const UPDATE_STORE_ERROR_ACTION = "UPDATE_STORE_ERROR_ACTION";
export const UPDATE_STORE_SUCCESS_ACTION = "UPDATE_STORE_SUCCESS_ACTION";
export const UPDATE_STORE_REMOVE_MSG_ACTION = "UPDATE_STORE_REMOVE_MSG_ACTION";

export const ADD_CONTRACT_FEATURE_ACTION = "ADD_CONTRACT_FEATURE_ACTION";
export const ADD_CONTRACT_FEATURE_ERROR_ACTION =
  "ADD_CONTRACT_FEATURE_ERROR_ACTION";
export const ADD_CONTRACT_FEATURE_SUCCESS_ACTION =
  "ADD_CONTRACT_FEATURE_SUCCESS_ACTION";
export const ADD_CONTRACT_FEATURE_DONE = "ADD_CONTRACT_FEATURE_DONE";

export const GET_CONTRACT_FEATURE_ACTION = "GET_CONTRACT_FEATURE_ACTION";
export const GET_CONTRACT_FEATURE_ERROR_ACTION =
  "GET_CONTRACT_FEATURE_ERROR_ACTION";
export const GET_CONTRACT_FEATURE_SUCCESS_ACTION =
  "GET_CONTRACT_FEATURE_SUCCESS_ACTION";

export const UPDATE_CONTRACT_FEATURE_ACTION = "UPDATE_CONTRACT_FEATURE_ACTION";
export const UPDATE_CONTRACT_FEATURE_ERROR_ACTION =
  "UPDATE_CONTRACT_FEATURE_ERROR_ACTION";
export const UPDATE_CONTRACT_FEATURE_SUCCESS_ACTION =
  "UPDATE_CONTRACT_FEATURE_SUCCESS_ACTION";
export const UPDATE_CONTRACT_FEATURE_DONE_ACTION =
  "UPDATE_CONTRACT_FEATURE_DONE_ACTION";

export const DELETE_CONTRACT_FEATURE_ACTION = "DELETE_CONTRACT_FEATURE_ACTION";
export const DELETE_CONTRACT_FEATURE_ERROR_ACTION =
  "DELETE_CONTRACT_FEATURE_ERROR_ACTION";
export const DELETE_CONTRACT_FEATURE_SUCCESS_ACTION =
  "DELETE_CONTRACT_FEATURE_SUCCESS_ACTION";
export const DELETE_CONTRACT_FEATURE_DONE_ACTION =
  "DELETE_CONTRACT_FEATURE_DONE_ACTION";

export const GET_CONTRACT_FEE_ACTION = "GET_CONTRACT_FEE_ACTION";
export const GET_CONTRACT_FEE_ERROR_ACTION = "GET_CONTRACT_FEE_ERROR_ACTION";
export const GET_CONTRACT_FEE_SUCCESS_ACTION =
  "GET_CONTRACT_FEE_SUCCESS_ACTION";

export const UPDATE_CONTRACT_FEE_ACTION = "UPDATE_CONTRACT_FEE_ACTION";
export const UPDATE_CONTRACT_FEE_ERROR_ACTION =
  "UPDATE_CONTRACT_FEE_ERROR_ACTION";
export const UPDATE_CONTRACT_FEE_SUCCESS_ACTION =
  "UPDATE_CONTRACT_FEE_SUCCESS_ACTION";
export const UPDATE_CONTRACT_FEE_DONE_ACTION =
  "UPDATE_CONTRACT_FEE_DONE_ACTION";
