apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*
      - ./infra/k8s/auth-depl.yaml
build:
  local:
    push: true

  artifacts:
  # - image:
    - image: communiqo/nft-client-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .

