export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_HOME_DATA = "GET_HOME_DATA";
export const GET_COLLECTION_DATA = "GET_COLLECTION_DATA";
export const POST_LOGIN_DATA = "POST_LOGIN_DATA";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const POST_CREATE_COLLECTION_DATA = "POST_CREATE_COLLECTION_DATA";
export const GET_CONTRACT_DATA = "GET_CONTRACT_DATA";
export const POST_NFT = "POST_NFT";
export const GET_MY_NFT = "GET_MY_NFT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_ALL_STORE_NFTS = "GET_ALL_STORE_NFTS";
export const GET_CURRENT_STORE_DATA = "GET_CURRENT_STORE_DATA";
export const GET_TOP_COLLECTIONS_DATA = "GET_TOP_COLLECTIONS_DATA";
export const GET_TOP_NFTS_DATA = " GET_TOP_NFTS_DATA";
export const GET_MY_COLLECTIONS_DATA = " GET_MY_COLLECTIONS_DATA";
export const SELL_NFT = "SELL_NFT";
export const GET_MY_COLLECTIONS_NFT = " GET_MY_COLLECTIONS_NFT";
export const BUY_NFT = "BUY_NFT";
export const UPDATE_NFT = "UPDATE_NFT";
export const GET_NFT = "GET_NFT";
export const GET_USER_NFT = "GET_USER_NFT";
export const MAKE_BID = "MAKE_BID";
export const DELETE_NFT = "DELETE_NFT";
export const GET_AUCTION_NFT = "GET_AUCTION_NFT";
export const VIEW_NFT_BIDS = "VIEW_NFT_BIDS";
export const APPROVE_NFT_BIDS = "APPROVE_NFT_BIDS";
export const VIEW_USER_DATA = "VIEW_USER_DATA";
export const CANCEL_NFT_DATA = "CANCEL_NFT_DATA";
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GET_HISTORY = "GET_HISTORY";
export const GET_SEARCH = "GET_SEARCH";
export const GET_FEE = "GET_FEE";
export const UPDATE_FEE = "UPDATE_FEE";
export const LOADER_FULL = "LOADER_FULL";
export const LOADER = "LOADER";
export const PLACE_BID = "PLACE_BID";
export const CANCEL_BID_DATA = "CANCEL_BID_DATA";
export const ADD_AUCTION_OFFER = "ADD_AUCTION_OFFER";
export const APPROVE_AUCTION_OFFER = "APPROVE_AUCTION_OFFER";
export const CANCEL_AUCTION_OFFER = "CANCEL_AUCTION_OFFER";
export const GET_HOME_EXPLORE_NFTS = "GET_HOME_EXPLORE_NFTS";
export const GET_BLOGS = "GET_BLOGS";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const GET_PAGES = "GET_PAGES";
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const POST_NOTIFICATION = "POST_NOTIFICATION";
export const GET_NOTIFICATION_SETTINGS = "GET_NOTIFICATION_SETTINGS";
export const REPORT = "REPORT";
export const GET_SEARCH_HISTORY = "GET_SEARCH_HISTORY";
export const POST_SEARCH_HISTORY = "POST_SEARCH_HISTORY";
export const DELETE_SEARCH_HISTORY = "DELETE_SEARCH_HISTORY";
export const POST_LIKE = "POST_LIKE";
export const POST_UNLIKE = "POST_UNLIKE";
export const POST_FOLLOW = "POST_FOLLOW";
export const POST_UNFOLLOW = "POST_UNFOLLOW";
export const GET_USER = "GET_USER";
export const POST_WISHLIST = "POST_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const PUT_WISHLIST = "PUT_WISHLIST";
export const PUT_HIDE_COLLECTION = "PUT_HIDE_COLLECTION";
export const GET_COLLECTION = "GET_COLLECTION";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETALLSTORENFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETALLSTORENFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETNFT";
export const BUY_SELL_MANUALLY_UPDATE_IN_GETALLSTORENFT =
  "BUY_SELL_MANUALLY_UPDATE_IN_GETALLSTORENFT";
export const BUY_SELL_MANUALLY_UPDATE_IN_GET_NFT =
  "BUY_SELL_MANUALLY_UPDATE_IN_GET_NFT";
export const GET_BLOG_CATEGORY = "GET_BLOG_CATEGORY";
export const GET_SOCIAL_MEDIA = "GET_SOCIAL_MEDIA";
export const WISHLIST_UNWISHLIST_MANUALLY_UPDATE_IN_GETALLSTORENFT =
  "WISHLIST_UNWISHLIST_MANUALLY_UPDATE_IN_GETALLSTORENFT";
export const WISHLIST_UNWISHLIST_MANUALLY_UPDATE_IN_GETNFT =
  "WISHLIST_UNWISHLIST_MANUALLY_UPDATE_IN_GETNFT";
export const FOLLOW_UNFOLLOW_MANUALLY_UPDATE_IN_GETUSERINFO =
  "FOLLOW_UNFOLLOW_MANUALLY_UPDATE_IN_GETUSERINFO";
export const POST_WITHDRAW_AUCTION_BID = "POST_WITHDRAW_AUCTION_BID";
export const POST_END_AUCTION = "POST_END_AUCTION";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETTOPNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETTOPNFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETAUCTIONNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETAUCTIONNFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETHOMEEXPLORENFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETHOMEEXPLORENFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_getUserNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_getUserNFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETMYNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GETMYNFT";
export const LIKE_UNLIKE_MANUALLY_UPDATE_IN_GetCollectionsNFT =
  "LIKE_UNLIKE_MANUALLY_UPDATE_IN_GetCollectionsNFT";
export const EDIT_SHARE_LISTING_FEE = "EDIT_SHARE_LISTING_FEE";
export const DELETE_SHARE_LISTING_FEE = "DELETE_SHARE_LISTING_FEE";
export const ADD_SHARE_LISTING_FEE = "ADD_SHARE_LISTING_FEE";
export const POST_TRANSFER = "POST_TRANSFER";
export const POST_MAKEANOFFER = "POST_MAKEANOFFER";
export const POST_ACCEPTOFFER = "POST_ACCEPTOFFER";
export const PUT_CANCELOFFER = "PUT_CANCELOFFER";
