/* AUTH */
export const LOGIN_ADMIN = "LOGIN_USER";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_ADMIN_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_ADMIN = "LOGOUT_USER";
export const LOGOUT_ADMIN_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_ADMIN_ERROR = "LOGOUT_USER_ERROR";
export const CHANGE_PASSWORD = "  CHANGE_NEW_PASSWORD";
export const CHANGE_ADMIN_ERROR = "CHANGE_ADMIN_ERROR";
export const CHANGE_ADMIN_SUCCESS = "CHANGE_ADMIN_SUCCESS";
