apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-nginx
spec:
  secretName: letsencrypt-nginx-private-key
  issuerRef:
    name: letsencrypt-nginx
    kind: Issuer
  dnsNames:
    - ''